### ISSUE TITLE
"Logged in." but "Error: 401: User not found"

### ISSUE THREAD

**Issue by persia7emily** [ArdaxHz/mangadex_bulk_uploader#2]
Manga id: √, chapter: 2, volume: None, title: None, language: zh-hk, groups: ['√'], publish on: None.
**Logged in.** 
Created upload session: √.
31 images to upload.
Uploading images 1 to 10.
Success: Uploaded page 01.png, size: 1445060 bytes.
……
Uploading images 11 to 20.
Success: Uploaded page 11.jpg, size: 1356547 bytes.
……
Uploading images 21 to 30.
Success: Uploaded page 21.jpg, size: 1056374 bytes.
……
Uploading images 31 to 31.
**Error: 401: User not found
Error: 401: User not found
Error: 401: User not found**
Deleting draft due to failed image upload: √
Failed uploads:
Folder: √

**Comment by ArdaxHz** [comment]
Can you show me the logs? Specifically the last part where it errors

**Comment by persia7emily** [comment]
> 

Amazing! nothing different but today it works~

**Comment by persia7emily** [comment]
> Prolly took too long to upload your account logged out

yeah you're right, i meet it again

**Comment by persia7emily** [comment]
> Can you show me the logs?

it ends with
```

Success: Uploaded page 10.jpg, size: 1390473 bytes.
Uploading images 11 to 20.
Error: 401: User not found
Error: 401: User not found
Error: 401: User not found
Deleting draft due to failed image upload: 62b9c5eb-7f2a-45fd-89c8-df9637af9110, Mamakatsu, Hajimemasu [zh-hk] - c03 [chui].
```
i am sure it depends on how the network goes
