### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by BaganLee** [ArdaxHz/mangadex_bulk_uploader#4]
Hello, I'm not sure if there is a solution or a workaround on this error, but I got an error saying that the images were too large and the uploader stopped. I thought that the uploader had the same factions as the uploader on the mDex site so I just went ahead and used it without asking. 

The exact error I got is:
![image](https://github.com/ArdaxHz/mangadex_bulk_uploader/assets/12983651/1c75ed2b-6337-4481-bc18-d70fb5259bda)

OS: Window 10
Python Version: 3.11

**Comment by ArdaxHz** [comment]
The images you're trying to upload have a height of 12k, which is higher than the 10k allowed by mangadex. You'll need to chop the images down to a smaller size.
